name: "Dotenv"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '23 12 * * 5'

jobs:
  analyze:
    name: Dotenv
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD

    - name: Checkout repository
      uses: actions/checkout@v2
      
=======
    - name: Checkout repository
      uses: actions/checkout@v2
          
>>>>>>> 8c89dad6d8589a0cc45b711264b3e2a596e22c0e
    - name: Install Dependencies
      run: npm install

    - name: create env file
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }} >> .env
  
    - name: Run app
      env:
        PORT: ${{ secrets.PORT }}
      run: node server
      
